### ISSUE TITLE
Miss translation string

### ISSUE THREAD

**Issue by burunduk** [ruggbean/More-Candles#2]
### Mod Version

1.1.0

### Modded

ACulinaryArtillery 1.0.12_RC
ExpandedFoods 1.6.6

### SP/MP

Singleplayer

### Description

```shell
In handbook i see "morecandles:block-chandelierlardcandle-black-candle8" string.
```

### How to Reproduce

```shell
Open hand book
Type 'candle8'
```

**Comment by ruggbean** [comment]
After typing in candle8, the return for my input was "morecandles:block-chandelierlardcandle-plain-candle8". I added the appropriate text and when I typed in candle8 once more, there was no input return.

![Capture](https://github.com/ruggbean/More-Candles/assets/109896152/ba28a46a-ff50-421c-aaa3-25832304cbaf)
![Capture3](https://github.com/ruggbean/More-Candles/assets/109896152/1a770adb-448c-41ec-b522-77743f49fa35)

I did not see the black lard chandelier in my input; please let me know if you meant plain lard chandelier instead of black lard chandelier. If your input is still showing up as black lard chandelier, could you show me a screenshot of your input so that I can see what you're looking at?

**Comment by burunduk** [comment]
I haven't checked yet.
I have such warnings in the logs, maybe they will be useful?
`
...
6.6.2023 07:57:40 [Warning] Texture asset 'morecandles:textures/block/wax/lardcandle/plain.png' not found (defined in Baked variant of block morecandles:chandelierlardcandle-plain-candle1).
...
6.6.2023 07:58:00 [Warning] Failed resolving a blocks blockdrop or smeltedstack with code morecandles:waxblock in tradehandbookinfo Торговець сільським господарством
6.6.2023 07:58:00 [Warning] Failed resolving a blocks blockdrop or smeltedstack with code morecandles:soyblock in tradehandbookinfo Торговець сільським господарством
6.6.2023 07:58:00 [Warning] Failed resolving a blocks blockdrop or smeltedstack with code morecandles:waxblock in tradehandbookinfo Торговець-ремісник
6.6.2023 07:58:00 [Warning] Failed resolving a blocks blockdrop or smeltedstack with code morecandles:soyblock in tradehandbookinfo Торговець-ремісник
6.6.2023 07:58:00 [Warning] Failed resolving a blocks blockdrop or smeltedstack with code morecandles:waxblock in tradehandbookinfo Торговець сировиною
6.6.2023 07:58:00 [Warning] Failed resolving a blocks blockdrop or smeltedstack with code morecandles:soyblock in tradehandbookinfo Торговець сировиною
6.6.2023 07:58:00 [Warning] Failed resolving a blocks itemdrop or smeltedstack with code morecandles:waxcandle in tradehandbookinfo Торговець скарбами
6.6.2023 07:58:00 [Warning] Failed resolving a blocks itemdrop or smeltedstack with code morecandles:soycandle in tradehandbookinfo Торговець скарбами
...
`

**Comment by ruggbean** [comment]
I have fixed the text for the plain lardcandle, and this will be in the next update. Thank you!
